-name: Install latest MySQL server 
apt: 
name=mysql-server
state=latest

-name: Start Mysql Service
service: 
name=mysql
state=started 
enabled=true

-name: Create a new database
mysql_db: 
name=demo
state=present 
collation=utf8_general_ci

-name: Create a database user
mysql_user:
name=demo 
password=demo priv=*.*:ALL 
host=localhost
state=present

-name: Insert sample.sql data
shell: cat /tmp/sample.sql | mysql -u demo -pdemo demo

-name: Copy sample.sql data
copy: src=sample.sql dest=/tmp/dump.sql

- name: 6. Install MySQL extension for PHP
  apt: 
name=php5-mysql 
state=present
